--
-- Database: `airbnb_clone`

USE `airbnb_clone`; 

--
-- Important Notice: The primary key in every table is generated by calling UUID() in the insert statements. 
-- Also, passwords are hashed password from implimenting mysql SHA2 algorithm. Samples of insert statements ran are also included. 
-- --------------------------------------------------------

--
-- Dumping data for table `booking`
--

-- one of sql statements originally ran to insert into booking:
-- INSERT INTO `booking`(`booking_id`, `property_id`, `user_id`, `start_date`, `end_date`, `total_price`, `status`)  
-- VALUES (UUID(),'0f6b53bc-54c8-11f0-b651-0a0027000014','69fa555d-54c5-11f0-b651-0a0027000014', '2025-08-15','2025-08-20',3306.0,'Confirmed');

INSERT INTO `booking` (`booking_id`, `property_id`, `user_id`, `start_date`, `end_date`, `total_price`, `status`, `created_at`) VALUES
('104314b5-54d1-11f0-b651-0a0027000014', '07cdff87-54c7-11f0-b651-0a0027000014', '441de6b3-54cf-11f0-b651-0a0027000014', '2025-08-15', '2025-08-16', '901', 'Confirmed', '2025-06-29 10:08:54'),
('6a1c29aa-54c9-11f0-b651-0a0027000014', '0f6b53bc-54c8-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', '2025-08-15', '2025-08-20', '3306', 'Confirmed', '2025-06-29 09:14:09');

-- --------------------------------------------------------

--
-- Dumping data for table `message`
--

-- sql statement originally ran to insert into message:
-- INSERT INTO `message`(`message_id`, `sender_id`, `message_body`) 
-- VALUES (UUID(),'ffa4ef6e-54c4-11f0-b651-0a0027000014','Payment received!');

INSERT INTO `message` (`message_id`, `sender_id`, `message_body`, `sent_at`) VALUES
('2055809c-54cc-11f0-b651-0a0027000014', 'ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Payment received!', '2025-06-29 09:33:34');

-- --------------------------------------------------------

--
-- Dumping data for table `message_recipient`
--

-- one of sql statements originally ran to insert into message_recipient:
-- INSERT INTO `message_recipient`(`message_id`, `recipient_id`) 
-- VALUES ('2055809c-54cc-11f0-b651-0a0027000014','69fa555d-54c5-11f0-b651-0a0027000014');

INSERT INTO `message_recipient` (`message_id`, `recipient_id`, `received_at`) VALUES
('2055809c-54cc-11f0-b651-0a0027000014', '441de6b3-54cf-11f0-b651-0a0027000014', '2025-06-29 10:15:02'),
('2055809c-54cc-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', '2025-06-29 09:36:23');

-- --------------------------------------------------------

--
-- Dumping data for table `payment`
--

-- one of sql statements originally ran to insert into payment:
-- INSERT INTO `payment`(`payment_id`, `booking_id`, `amount`, `payment_method`) 
-- VALUES (UUID(), '6a1c29aa-54c9-11f0-b651-0a0027000014', 2204.0,'Credit_Card');

INSERT INTO `payment` (`payment_id`, `booking_id`, `amount`, `payment_date`, `payment_method`) VALUES
('090c9300-54cb-11f0-b651-0a0027000014', '6a1c29aa-54c9-11f0-b651-0a0027000014', '1102', '2025-06-29 09:25:45', 'Paypal'),
('6c53c5e8-54d1-11f0-b651-0a0027000014', '104314b5-54d1-11f0-b651-0a0027000014', '901', '2025-06-29 10:11:29', 'Credit_Card'),
('d2d39411-54ca-11f0-b651-0a0027000014', '6a1c29aa-54c9-11f0-b651-0a0027000014', '2204', '2025-06-29 09:24:14', 'Credit_Card');

-- --------------------------------------------------------

--
-- Dumping data for table `property`
--

-- one of sql statements originally ran to insert into property:
-- INSERT INTO `property`(`property_id`, `host_id`, `name`, `description`, `location`, `price_per_night`) 
-- VALUES (UUID(),'ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Paradise is not Far', 'Tallest white building on the street','block 2A, Dimple Close, Ikoyi - Lagos',450.50);


INSERT INTO `property` (`property_id`, `host_id`, `name`, `description`, `location`, `price_per_night`, `created_at`, `updated_at`) VALUES
('07cdff87-54c7-11f0-b651-0a0027000014', 'ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Paradise is not Far', 'Tallest white building on the street', 'block 2A, Dimple Close, Ikoyi - Lagos', '451', '2025-06-29 08:57:05', NULL),
('0f6b53bc-54c8-11f0-b651-0a0027000014', 'ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Auto Palace', 'Best Catfish in town', '82, Opebi Ikeja, Lagos.', '551', '2025-06-29 09:04:27', NULL);

-- --------------------------------------------------------

--
-- Dumping data for table `review`
--

-- sql statement originally ran to insert into review:
-- INSERT INTO `review`(`review_id`, `property_id`, `user_id`, `rating`, `comment`) 
-- VALUES (UUID(),'0f6b53bc-54c8-11f0-b651-0a0027000014','69fa555d-54c5-11f0-b651-0a0027000014',5,'Top-notch!');


INSERT INTO `review` (`review_id`, `property_id`, `user_id`, `rating`, `comment`, `created_at`) VALUES
('a23698a3-54cb-11f0-b651-0a0027000014', '0f6b53bc-54c8-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', 5, 'Top-notch!', '2025-06-29 09:30:02');

-- --------------------------------------------------------

--
-- Dumping data for table `user`
--

-- one of sql statements originally ran for admin user:
-- INSERT INTO `user`(`user_id`, `first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `role`) 
-- VALUES (UUID(),'admin','admin','admin_airbnb_clone@gmail.com',SHA2('testgZvTtlPtjGRqeMBaLji3HxoKB5EZCsNL', 256), '2348123541234','Admin');

INSERT INTO `user` (`user_id`, `first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `role`, `created_at`) VALUES
('441de6b3-54cf-11f0-b651-0a0027000014', 'Abubakar', 'Yinuz', 'abu_yinuz@gmail.com', '54635d982c8726a84e754692fd73d3463cd7379d1b26aef22dd5621ed99729c6', NULL, 'Guest', '2025-06-29 09:56:02'),
('501ccf96-54c4-11f0-b651-0a0027000014', 'admin', 'admin', 'admin_airbnb_clone@gmail.com', '98cb4d888ce679185db300dd0e8a04ab11a8bd6c5cad42815e702c963b403e3d', '2348123541234', 'Admin', '2025-06-29 08:37:38'),
('69fa555d-54c5-11f0-b651-0a0027000014', 'Dan', 'Akpan', 'akpan_dan@gmail.com', 'e6b71590055b092a24b7276d1e614fa568cb95b7e06def90689faedc8992a142', '2347098128978', 'Guest', '2025-06-29 08:45:31'),
('ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Samuel', 'John', 'lifeisshort@gmail.com', 'c0ba3c9637e54a5d0c42d1dd192f542a16e91e6808b536cc0b118f42c9f8f2e2', '2348216723456', 'Host', '2025-06-29 08:42:32');

COMMIT;
