--
-- Database: `airbnb_clone`

USE `airbnb_clone`; 

--
-- Important Notice: The primary key in every table is generated by calling UUID() in the insert statements. 
-- Also, passwords are hashed password from implimenting mysql SHA2 algorithm. Samples of insert statements ran are also included. 
-- --------------------------------------------------------

--
-- Dumping data for table `user`
--


INSERT INTO `user` (`user_id`, `first_name`, `last_name`, `email`, `password_hash`, `phone_number`, `role`) VALUES
(UUID(), 'Abubakar', 'Yinuz', 'abu_yinuz@gmail.com', SHA2('t3lisc0pe', 256), NULL, 'GUEST', '2025-06-29 09:56:02'),
(UUID(), 'admin', 'admin', 'admin_airbnb_clone@gmail.com', SHA2('testgZvTtlPtjGRqeMBaLji3HxoKB5EZCsNL', 256), '2348123541234', 'ADMIN'),
(UUID(), 'Dan', 'Akpan', 'akpan_dan@gmail.com', SHA2('runn1ng_h0rse', 256), '2347098128978', 'GUEST'),
(UUID(), 'Samuel', 'John', 'lifeisshort@gmail.com', SHA2('1mm@tu@l', 256), '2348216723456', 'HOST'),
(UUID(), 'Ken', 'Williams', 'ken.willy@gmail.com', SHA2('Rumin@nt', 256), '2347914428912', 'GUEST');

-- post-execution
--
-- abu_yinuz@gmail.com          ->   id: '441de6b3-54cf-11f0-b651-0a0027000014'   
-- admin_airbnb_clone@gmail.com ->   id: '501ccf96-54c4-11f0-b651-0a0027000014'
-- akpan_dan@gmail.com          ->   id: '69fa555d-54c5-11f0-b651-0a0027000014'
-- lifeisshort@gmail.com        ->   id: 'ffa4ef6e-54c4-11f0-b651-0a0027000014'
-- --------------------------------------------------------

--
-- Dumping data for table `property`
--

INSERT INTO `property` (`property_id`, `host_id`, `name`, `description`, `location`, `price_per_night`) VALUES
(UUID(), 'ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Paradise is not Far', 'Tallest white building on the street', 'block 2A, Dimple Close, Ikoyi - Lagos', '451'),
(UUID(), 'ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Auto Palace', 'Best Catfish in town', '82, Opebi Ikeja, Lagos.', '551');

-- post-execution
--
-- property 'Paradise is not Far' ->   id:  '07cdff87-54c7-11f0-b651-0a0027000014'
-- property 'Auto Palace'         ->   id:  '0f6b53bc-54c8-11f0-b651-0a0027000014'
-- --------------------------------------------------------

--
-- Dumping data for table `property_feature`
--

INSERT INTO `property_feature` (`property_id`, `amenity`, `qty`) VALUES
('07cdff87-54c7-11f0-b651-0a0027000014', 'WI-FI', 1),
('07cdff87-54c7-11f0-b651-0a0027000014', 'POOL', 1),
('07cdff87-54c7-11f0-b651-0a0027000014', 'PET', 2),
('0f6b53bc-54c8-11f0-b651-0a0027000014', 'WI-FI', 1),
('0f6b53bc-54c8-11f0-b651-0a0027000014', 'POOL', 1);

-- post-execution
--
-- --------------------------------------------------------

--
-- Dumping data for table `booking`
--

INSERT INTO `booking` (`booking_id`, `property_id`, `user_id`, `start_date`, `end_date`, `total_price`, `status`) VALUES
(UUID(), '07cdff87-54c7-11f0-b651-0a0027000014', '441de6b3-54cf-11f0-b651-0a0027000014', '2025-08-15', '2025-08-16', '901', 'CONFIRMED'),
(UUID(), '0f6b53bc-54c8-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', '2025-08-15', '2025-08-20', '3306', 'CONFIRMED'),
(UUID(), '07cdff87-54c7-11f0-b651-0a0027000014', '8edc9fa4-5982-11f0-b651-0a0027000014', '2025-08-18', '2025-08-19', '901', 'PENDING'),
(UUID(), '0f6b53bc-54c8-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', '2025-08-22', '2025-08-27', '3306', 'CONFIRMED'),
(UUID(), '0f6b53bc-54c8-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', '2025-08-29', '2025-09-03', '3306', 'CONFIRMED')
(UUID(), '07cdff87-54c7-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', '2025-09-23', '2025-09-24', '901', 'PENDING'),;

-- post-execution
--
-- booking-1            ->   id:  '104314b5-54d1-11f0-b651-0a0027000014'
-- booking-2            ->   id:  '6a1c29aa-54c9-11f0-b651-0a0027000014'
-- booking-3            ->   id:  '1d5bb7d5-5985-11f0-b651-0a0027000014'
-- booking-4            ->   id:  '1d5bf97c-5985-11f0-b651-0a0027000014'
-- booking-5            ->   id:  '1d5bfd24-5985-11f0-b651-0a0027000014'
-- booking-6            ->   id:  'fb9a3907-5998-11f0-b651-0a0027000014'
-- --------------------------------------------------------

--
-- Dumping data for table `message`
--

INSERT INTO `message` (`message_id`, `sender_id`, `message_body`) VALUES
(UUID(), 'ffa4ef6e-54c4-11f0-b651-0a0027000014', 'Payment received!');

-- post-execution
--
-- message-1            ->   id:  '2055809c-54cc-11f0-b651-0a0027000014'
-- --------------------------------------------------------

--
-- Dumping data for table `message_recipient`
--

INSERT INTO `message_recipient` (`message_id`, `recipient_id`) VALUES
('2055809c-54cc-11f0-b651-0a0027000014', '441de6b3-54cf-11f0-b651-0a0027000014'),
('2055809c-54cc-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014');

-- post-execution
--
-- --------------------------------------------------------

--
-- Dumping data for table `payment`
--

INSERT INTO `payment` (`payment_id`, `booking_id`, `amount`, `payment_method`) VALUES
(UUID(), '6a1c29aa-54c9-11f0-b651-0a0027000014', '1102', 'PAYPAL'),
(UUID(), '104314b5-54d1-11f0-b651-0a0027000014', '901', 'CREDIT_CARD'),
(UUID(), '6a1c29aa-54c9-11f0-b651-0a0027000014', '2204', 'CREDIT_CARD'),
(UUID(), '1d5bb7d5-5985-11f0-b651-0a0027000014', '901', 'CREDIT_CARD'),
(UUID(), '1d5bf97c-5985-11f0-b651-0a0027000014', '3306', 'CREDIT_CARD'),
(UUID(), '1d5bfd24-5985-11f0-b651-0a0027000014', '3306', 'CREDIT_CARD'),
(UUID(), 'fb9a3907-5998-11f0-b651-0a0027000014', '901', 'CREDIT_CARD');

-- post-execution
--
-- payment-1            ->   id:  '090c9300-54cb-11f0-b651-0a0027000014'
-- payment-2            ->   id:  '6c53c5e8-54d1-11f0-b651-0a0027000014'
-- payment-3            ->   id:  'd2d39411-54ca-11f0-b651-0a0027000014'
-- payment-4            ->   id:  '143ba420-598e-11f0-b651-0a0027000014'
-- payment-5            ->   id:  '143c7fc0-598e-11f0-b651-0a0027000014'
-- payment-6            ->   id:  '143c81e0-598e-11f0-b651-0a0027000014'
-- --------------------------------------------------------

--
-- Dumping data for table `review`
--

INSERT INTO `review` (`review_id`, `property_id`, `user_id`, `rating`, `comment`) VALUES
(UUID(), '0f6b53bc-54c8-11f0-b651-0a0027000014', '69fa555d-54c5-11f0-b651-0a0027000014', 5, 'Top-notch!');

-- --------------------------------------------------------

COMMIT;
